# Generated by Django 2.2 on 2019-04-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movietreu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.TextField()),
                ('content', models.TextField()),
                ('data', models.DateField()),
                ('actor', models.CharField(max_length=20)),
                ('imgsrc', models.TextField()),
            ],
            options={
                'db_table': 'movietreu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('imgsrc', models.TextField()),
                ('price', models.CharField(max_length=20)),
                ('delete', models.IntegerField(db_column='Delete')),
            ],
            options={
                'db_table': 'phone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('introfuce', models.TextField()),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
    ]
